import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

import { buildCourseDetails, buildCourseSummaries } from "./course-data"

const sourcePath = resolve("courses.json")
const outputDirectory = resolve("app/data/generated")
const source = readFileSync(sourcePath, "utf8")
const input: unknown = JSON.parse(source)
const courses = buildCourseSummaries(input)
const output = JSON.stringify(courses) + "\n"
const detailsByTerm = buildCourseDetails(input)

mkdirSync(outputDirectory, { recursive: true })
writeFileSync(resolve(outputDirectory, "course-summaries.json"), output)

const loaders: string[] = []
for (const [termCode, details] of Object.entries(detailsByTerm)) {
  const filename = `course-details-${termCode}.json`
  const content = JSON.stringify(details) + "\n"
  writeFileSync(resolve(outputDirectory, filename), content)
  loaders.push(`  ${JSON.stringify(termCode)}: () => require("./${filename}"),`)
  console.log(`Details ${termCode}: ${Buffer.byteLength(content)} bytes.`)
}
writeFileSync(
  resolve(outputDirectory, "detailLoaders.ts"),
  [
    "// Generated by npm run data:prepare. Do not edit manually.",
    'import type { CourseDetailContent } from "../courseTypes"',
    "",
    "export const detailLoaders: Record<string, () => Record<string, CourseDetailContent>> = {",
    ...loaders,
    "}",
    "",
  ].join("\n"),
)

console.log(`Prepared ${courses.length} course records.`)
console.log(
  `Source: ${Buffer.byteLength(source)} bytes; summaries: ${Buffer.byteLength(output)} bytes.`,
)
